services:
    _defaults:
        public: true
        autowire: true
        
    Kematjaya\LeafletBundle\Twig\LeafletMapExtension:
        tags: ['twig.extension']
        
    Kematjaya\LeafletBundle\Type\LeafletMapType: ~
    Kematjaya\LeafletBundle\Calculator\DistanceCalculatorInterface:
        class: Kematjaya\LeafletBundle\Calculator\HaversineCalculator